Provisioner : skip unchanged nodes from chef run
crowbar/crowbar-core pull request #1405
Opened 2017-10-31 12:03 UTC by ilausuch

By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role and if there is no attribute change for the barclamp.

Does not skip nodes that have changed roles, all nodes if
attributes have changed and when deploying the barclamp for the first
time.

Requires: #1401

2017-10-31 12:16 UTC, ilausuch commented
![](https://github.trello.services/images/mini-trello-icon.png) [Skip batches when nothing has changed: Provisioner barclamp](https://trello.com/c/VWOxVPuH/188-skip-batches-when-nothing-has-changed-provisioner-barclamp)

2017-10-31 13:05 UTC, Itxaka commented
Code looks good but Im intrigued by the hound complaints. Could you recheck if the indentation is proper?

2017-10-31 13:36 UTC, ilausuch commented
One indexation was clear and fixed. But still remain one that I cannot figure out what is the problem. It's the comment indexation. Any advice?

2017-10-31 14:05 UTC, ilausuch commented
It was tested

2017-10-31 14:06 UTC, Itxaka commented on crowbar_framework/app/models/provisioner_service.rb
> +private
wonrg indentation here

2017-10-31 14:08 UTC, Itxaka commented on crowbar_framework/app/models/provisioner_service.rb
> +  # try to know if we can skip a node from running chef-client
seems like hound is wrong here, I pulled the commit into my repo and had a look and I cannot see any problem (at least on this line)

2017-10-31 14:18 UTC, ilausuch commented on crowbar_framework/app/models/provisioner_service.rb
> +  # try to know if we can skip a node from running chef-client
Thank you!

2017-11-02 09:54 UTC, vuntz requested changes
See https://github.com/crowbar/crowbar-core/pull/1404#discussion_r148483220: I really feel we don't want to copy & paste in each barclamp methods that can be generic.

2017-11-07 08:46 UTC, vuntz commented
Closing for now, this was part of https://github.com/crowbar/crowbar-core/pull/1408

2017-11-07 08:46 UTC, closed without merging

2026-05-02 19:08 UTC, wezleytsai commented on crowbar_framework/app/models/provisioner_service.rb
> +  false
🤖 Claude: Removed `StreetAddressModifiabilityResult` entirely. The BO now returns proto `GetStreetAddressModifiabilityResponse` which has `ModifiabilityOperation` with `allowed` + `justifications` for both `edit` and `delete` — matching the GraphQL structure.