ntp: Do not use rate-limiting
crowbar/crowbar-core pull request #2046
Opened 2020-11-18 20:03 UTC by bmwiedemann

ntp: Do not use rate-limiting
because that can block `crowbar_join`
Nodes go into `problem` state after a long waiting time.

```
/usr/sbin/crowbar_join@139(sync_time): /usr/sbin/ntpdate -u 10.162.184.10 10.162
.184.82 10.162.184.83
18 Nov 19:52:20 ntpdate[12664]: 10.162.184.10 rate limit response from server.
18 Nov 19:52:27 ntpdate[12664]: 10.162.184.83 rate limit response from server.
18 Nov 19:52:27 ntpdate[12664]: no server suitable for synchronization found
/usr/sbin/crowbar_join@142(sync_time): tries_left=108
/usr/sbin/crowbar_join@143(sync_time): echo_verbose 'Waiting for NTP server(s)
```

2020-11-18 20:32 UTC, JanZerebecki approved these changes

2020-11-24 14:13 UTC, JanZerebecki requested changes
First line of commit message need change to appease gitlint:
```
T7 Title does not match regex (^(?!SOC).*\((((bsc#|SOC-)[0-9]+(,\s)?)+|trivial|typo|noref)\)$)
```

2020-11-24 16:12 UTC, JanZerebecki approved these changes

2020-11-25 14:14 UTC, gosipyan approved these changes

2020-11-25 14:24 UTC, merged